# This is a basic workflow to help you get started with Actions

name: sample-workflow

# Controls when the workflow will run
on: [push]
  # Triggers the workflow on push or pull request events but only for the "main" branch
 
 
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  explore-first-github-workflow:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - run: echo "The job was automatically triggerred by a ${{ github.event_name }} event."
      - run: echo "The job is running on a ${{ runner.os }} server hosted by GitHub."
      - run: echo "The job is running on a ${{ runner.os }} server hosted by GitHub."
      - run: echo "Gtihub repository is ${{ github.repository }}"
      - name: Listing files in the directory
        run: |
         ls ${{ github.workspace }} 
